"""initial revision

Revision ID: 569fdce5dc17
Revises: 
Create Date: 2019-05-02 20:11:18.365183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569fdce5dc17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doublegis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('numbers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doublegis-html',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('html', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['doublegis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doublegis-html')
    op.drop_table('doublegis')
    # ### end Alembic commands ###
