"""add category

Revision ID: bbeb58686cf1
Revises: d4815eda9be8
Create Date: 2019-05-03 21:27:16.701450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeb58686cf1'
down_revision = 'd4815eda9be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doublegis', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doublegis', 'category')
    # ### end Alembic commands ###
