"""add category

Revision ID: d4815eda9be8
Revises: d5c24012010f
Create Date: 2019-05-03 21:23:42.076799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4815eda9be8'
down_revision = 'd5c24012010f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
